# Create a Rocky Linux based container that allows for testing the GroqWare software
# suite.  

FROM rockylinux/rockylinux:8.4
# Alternative docker repo quay.io/rockylinux/rockylinux:8.4
LABEL author="Groq, Inc." \
      version="0.10.0" \
      build-creator="Groq"

# This must match the version specificed for each SDK and O/S
ARG PYTHON_VER=39

# This is the specific GroqWare SDK Version.
ARG GROQ_SDK_VER=0.10.0

# The location of the groqware packages.  Change if not in the same directory as
# the Dockerfile. Note that the location needs to be within the local source tree.
ARG GROQ_FILES_DIR=./

# This is the user to install the miniconda package and also the default login
ARG GROQ_USER=groq
ARG CONDA_PATH=/home/${GROQ_USER}/miniconda3/condabin

# These are the ports required for GroqView, Jupyter and Neutron
EXPOSE 8080 \
       8439 \
       8888

ENV TZ=UTC

# Update the base image and install dependencies
RUN dnf makecache  && dnf upgrade-minimal -y && \
    dnf install -y epel-release && \
    dnf groupinstall "development tools" -y 

RUN dnf install -y \
    wget \
    cmake \
    collectd \
    python${PYTHON_VER} \
    python${PYTHON_VER}-devel

# Install the GroqWare Suite Developer Package
COPY ${GROQ_FILES_DIR}groq-common-${GROQ_SDK_VER}.x86_64.rpm /tmp/groq-common.rpm
COPY ${GROQ_FILES_DIR}groq-devtools-${GROQ_SDK_VER}.x86_64.rpm /tmp/groq-devtools.rpm

RUN dnf install  -y \
    /tmp/groq-common.rpm \
    /tmp/groq-devtools.rpm \
    && rm /tmp/groq-*.rpm

# Create the groq user, install Minicondaand and
# create the groqflow conda environment
RUN useradd  -r \
    -d /home/${GROQ_USER} \
    -s /bin/bash \
    -c "Groq User Account" \
    ${GROQ_USER} \
    # [Optional] Add sudo support. Omit if you don't need to install software after connecting.
    && dnf install -y sudo \
    && echo ${GROQ_USER} ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/${GROQ_USER}} \
    && chmod 0440 /etc/sudoers.d/${GROQ_USER}}

USER ${GROQ_USER}
WORKDIR /home/${GROQ_USER}

RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
RUN bash miniconda.sh -b
RUN $CONDA_PATH/conda init
RUN $CONDA_PATH/conda config --set auto_activate_base False
RUN $CONDA_PATH/conda create -n groqflow python=3.9
RUN echo "conda activate groqflow" >> ~/.bashrc
RUN $CONDA_PATH/conda run -n groqflow pip install --upgrade pip
RUN rm miniconda.sh

# Clone the GroqFlow and optionally the and GroqAPI Repositories
RUN git clone https://github.com/groq/groqflow.git
# [Optional]  Remove if you just want to explore Groqflow
RUN git clone https://github.com/groq/GroqAPI.git
RUN $CONDA_PATH/conda run -n groqflow pip install -e ./groqflow

# Install Netron and jupyter notebook
RUN $CONDA_PATH/conda run -n groqflow pip install netron
RUN $CONDA_PATH/conda run -n groqflow pip install jupyter